sudo: required
dist: trusty
before_install:
  - sudo apt-get install libxcb-keysyms1-dev

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang
  - gcc
  
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - cd ${DEPS_DIR}
  
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
  
  # Go to the Root directory  
  - cd ..

# Build steps
script:
  - mkdir build
  - cd build
  - ${DEPS_DIR}/cmake/bin/cmake -DCONTINUOUS_INTEGRATION_RUN=ON -G "Unix Makefiles" .. && make